### ISSUE TITLE
ROMs - Add customizations capabilities for version/release/ascii logo

### ISSUE THREAD

**Issue by strus38** [bluebanquise/bluebanquise-infrastructure#5]
**Enhancement request**

- **Subject**: ROMs - Add customizations capabilities for version/release/logo
- **Reasons**: 
    * Ascii Logo customization: even if the T800 logo is awesome, it could be too much for some use cases, and as such, offering the possibility to exchange it by something else could be very nice 👍 
    * Version/release: also here, the version and release is something that may be versatile enough to be changed easily.

Thanks!

**Comment by oxedions** [comment]
Dear @strus38 

I will have a look on this. I need to provide at least a better way to build rpms.
